AWSTemplateFormatVersion: 2010-09-09

Description: This template can be used in CloudFormation to deploy a role, volume, and f1 instance

Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt EC2.AvailabilityZone
      Encrypted: true
      KmsKeyId: !Ref KmsKeyId
      Size: !Ref VolSize
      Tags:
        - Key: BusinessUnit
          Value: NGS
      VolumeType: !Ref VolType
  VolumeAttachment:
      Type: AWS::EC2::VolumeAttachment
      Properties:
        Device: !Ref DeviceName
        InstanceId: !Ref EC2
        VolumeId: !Ref Volume

  S3Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
      Path: /