AWSTemplateFormatVersion: 2010-09-09

Description: This template can be used in CloudFormation to deploy a role, volume, and f1 instance

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: The AMI Id for the Dragen image
    Default: "ami-0253643e935bd5c9c"
  InstanceType:
    Type: String
    Description: The type of instance to be deployed
    Default: "f1.2xlarge"
    AllowedValues:
    - "f1.2xlarge"
    - "f1.4xlarge"
  KeyName:
    Type: String
    Description: The key used to SSH into the f1
    Default: "NGS-key01"
    AllowedValues:
    - NGS-key01  
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group Id
    Default: "sg-071e8edf7bdbcd862"  
  SubnetId:
    Type: String
    Description: Subnet Id
    Default: "subnet-0f9186e42fd71b1af" 
  KmsKeyId:
    Type: String
    Description: KMS key Id
    Default: "arn:aws:kms:us-east-2:522085032638:key/bf3e8d8b-3cab-4395-b4bd-9f50e7a462c1"
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt EC2.AvailabilityZone
      Encrypted: true
      KmsKeyId: !Ref KmsKeyId
      Size: !Ref VolSize
      Tags:
        - Key: BusinessUnit
          Value: NGS
      VolumeType: !Ref VolType
  VolumeAttachment:
      Type: AWS::EC2::VolumeAttachment
      Properties:
        Device: !Ref DeviceName
        InstanceId: !Ref EC2
        VolumeId: !Ref Volume

  S3Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
      Path: /

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2InstanceProfile
      Roles:
        - !Ref S3Role