Resources:
  TestS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: AHEAD.S3.Test.Bucket

  TestS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Statement: 
      Sid: SingleIPAllow
      Effect: Deny
      Principal: "*"
      Action: s3:PutObject
      Resource: ARN: arn:aws:s3:::s3testbucket-tests3bucket-ln3i7tdyt8gp
      Condition: NotIpAddress: aws:SourceIp: 207.181.210.113

#MBP external IP: same   
#iMac external IP: 207.181.210.113

#Goal is limit bucket access to a specific IP