AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Parameter Store value for Primary Dragen Linux AMI

Parameters:
  LinuxPrimaryDragenAmiId:
    Type: String
    Default: "ami-0253643e935bd5c9c "
    Description: Primary AMI id for Linux Primary Dragen Instance

Resources:
  LinuxDragenPrimaryParameterStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ec2-ami-linux-primary-dragen
      Type: String
      Value: !Ref LinuxPrimaryDragenAmiId
      Description: Primary AMI id for Linux Dragen Instance